<?php

namespace App\Filament\Resources\Players\Tables;

use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Table;

class PlayersTable
{
    public static function configure(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name')
                    ->searchable(),
                TextColumn::make('group_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('account_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('level')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('vocation')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('health')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('healthmax')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('experience')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lookbody')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lookfeet')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lookhead')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('looklegs')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('looktype')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lookaddons')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('direction')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('maglevel')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('mana')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('manamax')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('manaspent')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('soul')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('town_id')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('posx')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('posy')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('posz')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('conditions'),
                TextColumn::make('cap')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('sex')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lastlogin')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lastip')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('save')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skull')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skulltime')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('lastlogout')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('blessings')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('onlinetime')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('deletion')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('balance')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('offlinetraining_time')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('offlinetraining_skill')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('stamina')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_fist')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_fist_tries')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_club')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_club_tries')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_sword')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_sword_tries')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_axe')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_axe_tries')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_dist')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_dist_tries')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_shielding')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_shielding_tries')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_fishing')
                    ->numeric()
                    ->sortable(),
                TextColumn::make('skill_fishing_tries')
                    ->numeric()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->recordActions([
                EditAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }
}
